### ISSUE TITLE
[Errno 13] Permission denied

### ISSUE THREAD

**Issue by myrainbowandsky** [SMAPPNYU/urlExpander#10]
`unable to cache TLDs in file /Library/Python/3.7/site-packages/tldextract/.tld_set: [Errno 13] Permission denied: '/Library/Python/3.7/site-packages/tldextract/.tld_set'`

mac 10.15.5
python3.7
when using urlexpander

**Comment by mabrownnyu** [comment]
@myrainbowandsky this seems to be an issue with `tldextract` rather than `urlexpander`, please report the issue there: https://github.com/john-kurkowski/tldextract/issues/
